PHP 8 + PHPUnit 9.4
ralouphie/mimey pull request #24
Opened 2020-11-30 15:43 UTC by rodolfoberrios

Hi,

This one adds support for PHP 8 and PHPUnit 9.4. I had to drop support for 5.4.

Tested locally with 7.4 + 8.0. Travis passing.

2020-12-11 15:26 UTC, Xantios commented
Can someone please merge this so I can pull this down from packagist ?:-) Thanks !

2020-12-11 15:28 UTC, peter279k commented
pin @ralouphie.

2020-12-11 15:28 UTC, peter279k approved these changes

2020-12-19 19:42 UTC, dmyers commented
I'm wondering if this is even maintained anymore. The last commit to `develop` was from March 2019.

2020-12-20 15:04 UTC, Xantios commented
> I'm wondering if this is even maintained anymore. The last commit to `develop` was from March 2019.

I Assumed the same. so i forked this repo and made sure it works in PHP 8.
https://github.com/xantios/mimey

I just added a custom VCS entry to my composer file, but if there is any interest I can push it to packagist

2020-12-21 12:29 UTC, peter279k commented
Pin @ralouphie.

2020-12-24 07:52 UTC, pvsaintpe approved these changes

2020-12-27 17:15 UTC, pvsaintpe requested changes

2020-12-27 17:15 UTC, pvsaintpe commented on .travis.yml
> +  - nightly
Please, add 8.0

2020-12-27 17:15 UTC, pvsaintpe commented
@ralouphie, @rodolfoberrios 

We really need support in our project:
 - php: ^8.0
 - phpunit/phpunit: ^9.5
 - php-coverals: ^2.0

When can we expect a release with these changes? I really don't want to make forks and other crutches ..

Thank you in advance.

2020-12-28 13:27 UTC, rodolfoberrios commented
@pvsaintpe 

I just contributed a few lines, I'm not the maintainer of this project. It seems that the person in charge isn't around, and likely it won't appear if you just keep mention this issue. Please don't push, it doesn't bring anything constructive imo.It will sound harsh, but if you really need this so bad then consider to fork it and maintain it. Otherwise you will be fall in the same situation with other maintainers not matching your release schedule requirements.

2021-01-08 23:08 UTC, pvsaintpe approved these changes

2021-01-18 14:33 UTC, vedro-compota commented
@ralouphie this needed

2021-01-21 13:01 UTC, vedro-compota commented
Guys we need some fork or does anyone have contact of the Author?

2021-01-21 14:06 UTC, rodolfoberrios commented
I'm done, sorry.

2021-01-21 14:06 UTC, closed without merging

2021-01-22 13:05 UTC, Xantios commented
> Guys we need some fork or does anyone have contact of the Author?
> @Xantios yes, packagist for this pack is needed too, because of recurs. dependencies.

You can add a VCS entry to your composer file and pull my fork in.
If there are more people wanting to maintain it, feel free to PR on that fork I will setup some composer stuff around it later today

2021-01-22 15:25 UTC, Xantios commented
@rodolfoberrios No worries! 👍 Thanks for figuring this out!
@vedro-compota Check out my fork on https://github.com/xantios/mimey

For all, if you want to PR something, feel free to PR my fork 👍

2021-01-22 15:46 UTC, peter279k commented
> @rodolfoberrios No worries!  Thanks for figuring this out!
> @vedro-compota Check out my fork on https://github.com/xantios/mimey
> 
> For all, if you want to PR something, feel free to PR my fork

@Xantios, thanks a lot!

2021-01-22 15:46 UTC, peter279k commented
@Xantios, btw, could you create the issue on your forked repository?

2021-01-22 15:48 UTC, Xantios commented
> @Xantios, BTW, could you create the issue on your forked repository?

The issue (PHP 8 / PHPUnit 9.4 support) is already merged in on the fork :-)

2021-01-22 15:55 UTC, peter279k commented
> > @Xantios, BTW, could you create the issue on your forked repository?
> 
> The issue (PHP 8 / PHPUnit 9.4 support) is already merged in on the fork :-)

Sorry. I mean could you enable issue setting on your forked repository?

You can enable the issue like following picture:

![image](https://user-images.githubusercontent.com/9021747/105513455-49db5100-5d0d-11eb-8892-de7adc70c6af.png)

2021-01-22 15:58 UTC, Xantios commented
Done! @peter279k

2022-03-04 10:43 UTC, Radon8472 commented
You should remove

```php
protected function setUp(): void
```
From you PR, this breaks compatibility to older php versions